[package]
name = "turbolift"
version = "0.1.0"
authors = ["Dominic Burkart <@DominicBurkart>"]
edition = "2018"
description = "WIP"
readme = "README.md"
license = "MIT OR BSD-2-Clause OR GPL-2.0+"

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"
serde = "1"
futures = "0.3"
proc-macro2 = "1.0"