[package]
name = "turbolift"
version = "0.1.0"
authors = ["Dominic Burkart <@DominicBurkart>"]
edition = "2018"
description = "WIP"
readme = "README.md"
license = "MIT OR BSD-3-Clause OR GPL-2.0+"

[dependencies]
turbolift_macros = { path="./turbolift_macros" }
turbolift_internals = { path="./turbolift_internals" }