[package]
name = "kubernetes_example"
version = "0.1.0"
authors = ["Dominic Burkart <1351120+DominicBurkart@users.noreply.github.com>"]
edition = "2018"

[features]
"distributed" = ["turbolift/distributed"]

[dependencies]
turbolift = { path="../../" }