name: docker

on:
  push:
    branches: master
  pull_request:
    branches: [ master ]

jobs:
  local_queue_example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build local queue example
        run: docker build -f examples/local_queue_example/Dockerfile .