name: rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy
    - name: Check
      run: RUSTFLAGS='--cfg procmacro2_semver_exempt' cargo check
    - name: Format
      run: RUSTFLAGS='--cfg procmacro2_semver_exempt' cargo fmt
    - name: Clippy
      run: RUSTFLAGS='--cfg procmacro2_semver_exempt' cargo clippy -- -D warnings
    - name: Local Queue
      run: cd examples/local_queue_example && RUSTFLAGS='--cfg procmacro2_semver_exempt' cargo test --verbose

