name: rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lints:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          profile: default
          toolchain: nightly
          override: true
    - name: Rustup
      run: rustup update
    - name: Format
      run: RUSTFLAGS='--cfg procmacro2_semver_exempt' cargo fmt
    - name: Check without distributed feature
      run: RUSTFLAGS='--cfg procmacro2_semver_exempt' cargo check
    - name: Check with distributed feature
      run: RUSTFLAGS='--cfg procmacro2_semver_exempt' cargo check --features "distributed"
    - name: Clippy
      run: RUSTFLAGS='--cfg procmacro2_semver_exempt' cargo clippy -- -D warnings
